spring:
  application:
    name: config
  profiles:
    active: composite
  cloud:
    config:
      discovery:
        enabled: true
      server:
        composite:
          - type: native
            search-locations: classpath:configuration
        bootstrap: true
server:
  port: 8888