spring:
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb:http://ORDER
          predicates:
            - Path=/burger-api/order/**
          filters:
            - HeaderFilter
            - RewritePath=/burger-api/(?<segment>.*), /$\{segment}
        - id: user
          uri: lb:http://USER
          predicates:
            - Path=/burger-api/user/**
          filters:
            - HeaderFilter
            - RewritePath=/burger-api/(?<segment>.*), /$\{segment}